FROM ubuntu:16.04
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install jupyter
WORKDIR /opt
RUN jupyter notebook --ip=0.0.0.0 --port=8080 --allow-root


export LANGUAGE=zh_CN.UTF-8
export LANG=zh_CN.UTF-8
export LC_ALL=zh_CN.UTF-8
locale-gen zh_CN.UTF-8
dpkg-reconfigure locales
